GET http://localhost:3000/places?text=av governador valadares, betim, 1000

###

GET http://localhost:3000/places?text=av amazonas, belo horizonte, 1000

###
@originId = ChIJgUaiCqCcmAARTur7mTUSUe4
@destinationId = ChIJvSzFjs5ZzpQRjKTDjcPluI4

### 
GET http://localhost:3000/directions=originId=&destinationId

###
GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "Rota 1",
    "source_id": "{{originId}}",
    "destination_id": "{{destinationId}}"
}

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/67587b1277379dca02d1f07d